#!/usr/bin/env crystal

# Crystal gRPC Code Generator
# Reads FileDescriptorSet from stdin and generates Crystal stubs

require "./crystal-grpc"
require "./crystal-grpc/protobuf/descriptor"
require "./crystal-grpc/protobuf/generator"

# Read FileDescriptorSet from stdin
input = STDIN.gets_to_end
data = input.to_slice

# Parse the FileDescriptorSet
files = Protobuf::DescriptorParser.parse(data)

if files.empty?
  STDERR.puts "Error: No file descriptors found in input"
  exit 1
end

# Generate Crystal code
generator = Protobuf::CodeGenerator.new
output = generator.generate(files)

# Write generated code to stdout
puts "# Generated by crystal-grpc code generator"
puts "# Do not edit manually"
puts ""
puts "require \"crystal-grpc\""
puts ""
puts output
